
module.exports = {
  Korone: require('./korone'),
  Woof: require('./woof'),
  Youtube: require('./youtube'),
  Confess: require('./confess'),
  Anime: require('./anime'),
  Seiyuu: require('./seiyuu'),
  Manga: require('./manga'),
  Vtuber: require('./vtuber'),
  Nh: require('./nh'),
  Whatanime: require('./whatanime'),
  Apod: require('./apod'),
  panjangtitid: require('./panjangtitit'),
  adutitid: require('./adutitid'),
  ngocok: require('./ngocok'),
  janken: require('./janken'),
  args: require('./args'),
  // stopbattle: require('./stopbattle'),
  // battleroyale: require('./battleroyale'),
};
